/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimberRouteImport } from './routes/timber'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PosRouteImport } from './routes/pos'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const TimberRoute = TimberRouteImport.update({
  id: '/timber',
  path: '/timber',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/timber': typeof TimberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/timber': typeof TimberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/inventory': typeof InventoryRoute
  '/pos': typeof PosRoute
  '/reports': typeof ReportsRoute
  '/timber': typeof TimberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/customers' | '/inventory' | '/pos' | '/reports' | '/timber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/customers' | '/inventory' | '/pos' | '/reports' | '/timber'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/inventory'
    | '/pos'
    | '/reports'
    | '/timber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  InventoryRoute: typeof InventoryRoute
  PosRoute: typeof PosRoute
  ReportsRoute: typeof ReportsRoute
  TimberRoute: typeof TimberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timber': {
      id: '/timber'
      path: '/timber'
      fullPath: '/timber'
      preLoaderRoute: typeof TimberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  InventoryRoute: InventoryRoute,
  PosRoute: PosRoute,
  ReportsRoute: ReportsRoute,
  TimberRoute: TimberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
